[package]
name = "zodl-slipstream-gpuhash"
description = "GPU-accelerated Orchard Sinsemilla MerkleCRH"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
wgpu = { workspace = true }
pollster = { workspace = true }
bytemuck = { workspace = true }
pasta_curves = { workspace = true }
sinsemilla = { workspace = true }
group = { workspace = true }
ff = { workspace = true }

[dev-dependencies]
orchard = { workspace = true }
incrementalmerkletree = { workspace = true }
rand = { workspace = true }
