// This file is @generated by prost-build.
/// ChainMetadata represents information about the state of the chain as of a given block.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChainMetadata {
    /// the size of the Sapling note commitment tree as of the end of this block
    #[prost(uint32, tag = "1")]
    pub sapling_commitment_tree_size: u32,
    /// the size of the Orchard note commitment tree as of the end of this block
    #[prost(uint32, tag = "2")]
    pub orchard_commitment_tree_size: u32,
}
/// CompactBlock is a packaging of ONLY the data from a block that's needed to:
///
/// 1. Detect a payment to your shielded Sapling address
/// 1. Detect a spend of your shielded Sapling notes
/// 1. Update your witnesses to generate new Sapling spend proofs.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactBlock {
    /// the version of this wire format, for storage
    #[prost(uint32, tag = "1")]
    pub proto_version: u32,
    /// the height of this block
    #[prost(uint64, tag = "2")]
    pub height: u64,
    /// the ID (hash) of this block, same as in block explorers
    #[prost(bytes = "vec", tag = "3")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    /// the ID (hash) of this block's predecessor
    #[prost(bytes = "vec", tag = "4")]
    pub prev_hash: ::prost::alloc::vec::Vec<u8>,
    /// Unix epoch time when the block was mined
    #[prost(uint32, tag = "5")]
    pub time: u32,
    /// (hash, prevHash, and time) OR (full header)
    #[prost(bytes = "vec", tag = "6")]
    pub header: ::prost::alloc::vec::Vec<u8>,
    /// zero or more compact transactions from this block
    #[prost(message, repeated, tag = "7")]
    pub vtx: ::prost::alloc::vec::Vec<CompactTx>,
    /// information about the state of the chain as of this block
    #[prost(message, optional, tag = "8")]
    pub chain_metadata: ::core::option::Option<ChainMetadata>,
}
/// CompactTx contains the minimum information for a wallet to know if this transaction
/// is relevant to it (either pays to it or spends from it) via shielded elements
/// only. This message will not encode a transparent-to-transparent transaction.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactTx {
    /// Index and hash will allow the receiver to call out to chain
    /// explorers or other data structures to retrieve more information
    /// about this transaction.
    ///
    /// the index within the full block
    #[prost(uint64, tag = "1")]
    pub index: u64,
    /// the ID (hash) of this transaction, same as in block explorers
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    /// The transaction fee: present if server can provide. In the case of a
    /// stateless server and a transaction with transparent inputs, this will be
    /// unset because the calculation requires reference to prior transactions.
    /// If there are no transparent inputs, the fee will be calculable as:
    /// valueBalanceSapling + valueBalanceOrchard + sum(vPubNew) - sum(vPubOld) - sum(tOut)
    #[prost(uint32, tag = "3")]
    pub fee: u32,
    #[prost(message, repeated, tag = "4")]
    pub spends: ::prost::alloc::vec::Vec<CompactSaplingSpend>,
    #[prost(message, repeated, tag = "5")]
    pub outputs: ::prost::alloc::vec::Vec<CompactSaplingOutput>,
    #[prost(message, repeated, tag = "6")]
    pub actions: ::prost::alloc::vec::Vec<CompactOrchardAction>,
}
/// CompactSaplingSpend is a Sapling Spend Description as described in 7.3 of the Zcash
/// protocol specification.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompactSaplingSpend {
    /// nullifier (see the Zcash protocol specification)
    #[prost(bytes = "vec", tag = "1")]
    pub nf: ::prost::alloc::vec::Vec<u8>,
}
/// output encodes the `cmu` field, `ephemeralKey` field, and a 52-byte prefix of the
/// `encCiphertext` field of a Sapling Output Description. These fields are described in
/// section 7.4 of the Zcash protocol spec:
/// <https://zips.z.cash/protocol/protocol.pdf#outputencodingandconsensus>
/// Total size is 116 bytes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompactSaplingOutput {
    /// note commitment u-coordinate
    #[prost(bytes = "vec", tag = "1")]
    pub cmu: ::prost::alloc::vec::Vec<u8>,
    /// ephemeral public key
    #[prost(bytes = "vec", tag = "2")]
    pub ephemeral_key: ::prost::alloc::vec::Vec<u8>,
    /// first 52 bytes of ciphertext
    #[prost(bytes = "vec", tag = "3")]
    pub ciphertext: ::prost::alloc::vec::Vec<u8>,
}
/// <https://github.com/zcash/zips/blob/main/zip-0225.rst#orchard-action-description-orchardaction>
/// (but not all fields are needed)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompactOrchardAction {
    /// \[32\] The nullifier of the input note
    #[prost(bytes = "vec", tag = "1")]
    pub nullifier: ::prost::alloc::vec::Vec<u8>,
    /// \[32\] The x-coordinate of the note commitment for the output note
    #[prost(bytes = "vec", tag = "2")]
    pub cmx: ::prost::alloc::vec::Vec<u8>,
    /// \[32\] An encoding of an ephemeral Pallas public key
    #[prost(bytes = "vec", tag = "3")]
    pub ephemeral_key: ::prost::alloc::vec::Vec<u8>,
    /// \[52\] The first 52 bytes of the encCiphertext field
    #[prost(bytes = "vec", tag = "4")]
    pub ciphertext: ::prost::alloc::vec::Vec<u8>,
}
/// BlockRange specifies a series of blocks from start to end inclusive.
/// Both BlockIDs must be heights; specification by hash is not yet supported.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlockRange {
    #[prost(message, optional, tag = "1")]
    pub start: ::core::option::Option<::zcash_client_backend::proto::service::BlockId>,
    #[prost(message, optional, tag = "2")]
    pub end: ::core::option::Option<::zcash_client_backend::proto::service::BlockId>,
}
/// A TxFilter contains the information needed to identify a particular
/// transaction: either a block and an index, or a direct transaction hash.
/// Currently, only specification by hash is supported.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TxFilter {
    /// block identifier, height or hash
    #[prost(message, optional, tag = "1")]
    pub block: ::core::option::Option<::zcash_client_backend::proto::service::BlockId>,
    /// index within the block
    #[prost(uint64, tag = "2")]
    pub index: u64,
    /// transaction ID (hash, txid)
    #[prost(bytes = "vec", tag = "3")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
/// A SendResponse encodes an error code and a string. It is currently used
/// only by SendTransaction(). If error code is zero, the operation was
/// successful; if non-zero, it and the message specify the failure.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendResponse {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
/// Chainspec is a placeholder to allow specification of a particular chain fork.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChainSpec {}
/// LightdInfo returns various information about this lightwalletd instance
/// and the state of the blockchain.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LightdInfo {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub vendor: ::prost::alloc::string::String,
    /// true
    #[prost(bool, tag = "3")]
    pub taddr_support: bool,
    /// either "main" or "test"
    #[prost(string, tag = "4")]
    pub chain_name: ::prost::alloc::string::String,
    /// depends on mainnet or testnet
    #[prost(uint64, tag = "5")]
    pub sapling_activation_height: u64,
    /// protocol identifier, see consensus/upgrades.cpp
    #[prost(string, tag = "6")]
    pub consensus_branch_id: ::prost::alloc::string::String,
    /// latest block on the best chain
    #[prost(uint64, tag = "7")]
    pub block_height: u64,
    #[prost(string, tag = "8")]
    pub git_commit: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub branch: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub build_date: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub build_user: ::prost::alloc::string::String,
    /// less than tip height if zcashd is syncing
    #[prost(uint64, tag = "12")]
    pub estimated_height: u64,
    /// example: "v4.1.1-877212414"
    #[prost(string, tag = "13")]
    pub zcashd_build: ::prost::alloc::string::String,
    /// example: "/MagicBean:4.1.1/"
    #[prost(string, tag = "14")]
    pub zcashd_subversion: ::prost::alloc::string::String,
}
/// TransparentAddressBlockFilter restricts the results to the given address
/// or block range.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransparentAddressBlockFilter {
    /// t-address
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// start, end heights
    #[prost(message, optional, tag = "2")]
    pub range: ::core::option::Option<BlockRange>,
}
/// Duration is currently used only for testing, so that the Ping rpc
/// can simulate a delay, to create many simultaneous connections. Units
/// are microseconds.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Duration {
    #[prost(int64, tag = "1")]
    pub interval_us: i64,
}
/// PingResponse is used to indicate concurrency, how many Ping rpcs
/// are executing upon entry and upon exit (after the delay).
/// This rpc is used for testing only.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingResponse {
    #[prost(int64, tag = "1")]
    pub entry: i64,
    #[prost(int64, tag = "2")]
    pub exit: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Address {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddressList {
    #[prost(string, repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Balance {
    #[prost(int64, tag = "1")]
    pub value_zat: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Exclude {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub txid: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSubtreeRootsArg {
    /// Index identifying where to start returning subtree roots
    #[prost(uint32, tag = "1")]
    pub start_index: u32,
    /// Shielded protocol to return subtree roots for
    #[prost(enumeration = "ShieldedProtocol", tag = "2")]
    pub shielded_protocol: i32,
    /// Maximum number of entries to return, or 0 for all entries.
    #[prost(uint32, tag = "3")]
    pub max_entries: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubtreeRoot {
    /// The 32-byte Merkle root of the subtree.
    #[prost(bytes = "vec", tag = "2")]
    pub root_hash: ::prost::alloc::vec::Vec<u8>,
    /// The hash of the block that completed this subtree.
    #[prost(bytes = "vec", tag = "3")]
    pub completing_block_hash: ::prost::alloc::vec::Vec<u8>,
    /// The height of the block that completed this subtree in the main chain.
    #[prost(uint64, tag = "4")]
    pub completing_block_height: u64,
}
/// Results are sorted by height, which makes it easy to issue another
/// request that picks up from where the previous left off.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAddressUtxosArg {
    #[prost(string, repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, tag = "2")]
    pub start_height: u64,
    /// zero means unlimited
    #[prost(uint32, tag = "3")]
    pub max_entries: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAddressUtxosReplyList {
    #[prost(message, repeated, tag = "1")]
    pub address_utxos:
        ::prost::alloc::vec::Vec<::zcash_client_backend::proto::service::GetAddressUtxosReply>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ShieldedProtocol {
    Sapling = 0,
    Orchard = 1,
}
impl ShieldedProtocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Sapling => "sapling",
            Self::Orchard => "orchard",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "sapling" => Some(Self::Sapling),
            "orchard" => Some(Self::Orchard),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod compact_tx_streamer_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    #[derive(Debug, Clone)]
    pub struct CompactTxStreamerClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CompactTxStreamerClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CompactTxStreamerClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CompactTxStreamerClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                    http::Request<tonic::body::Body>,
                    Response = http::Response<
                        <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                    >,
                >,
            <T as tonic::codegen::Service<http::Request<tonic::body::Body>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CompactTxStreamerClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Return the height of the tip of the best chain
        pub async fn get_latest_block(
            &mut self,
            request: impl tonic::IntoRequest<super::ChainSpec>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::BlockId>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLatestBlock",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetLatestBlock",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Return the compact block corresponding to the given block identifier
        pub async fn get_block(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::BlockId>,
        ) -> std::result::Result<tonic::Response<super::CompactBlock>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlock",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetBlock",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Same as GetBlock except actions contain only nullifiers
        pub async fn get_block_nullifiers(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::BlockId>,
        ) -> std::result::Result<tonic::Response<super::CompactBlock>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockNullifiers",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetBlockNullifiers",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Return a list of consecutive compact blocks
        pub async fn get_block_range(
            &mut self,
            request: impl tonic::IntoRequest<super::BlockRange>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::CompactBlock>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockRange",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetBlockRange",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Same as GetBlockRange except actions contain only nullifiers
        pub async fn get_block_range_nullifiers(
            &mut self,
            request: impl tonic::IntoRequest<super::BlockRange>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::CompactBlock>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockRangeNullifiers",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetBlockRangeNullifiers",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Return the requested full (not compact) transaction (as from zcashd)
        pub async fn get_transaction(
            &mut self,
            request: impl tonic::IntoRequest<super::TxFilter>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::RawTransaction>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTransaction",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetTransaction",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Submit the given transaction to the Zcash network
        pub async fn send_transaction(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::RawTransaction>,
        ) -> std::result::Result<tonic::Response<super::SendResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/SendTransaction",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "SendTransaction",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Return the transactions corresponding to the given t-address within the given block range
        /// NB - this method is misnamed, it returns transactions, not transaction IDs.
        pub async fn get_taddress_txids(
            &mut self,
            request: impl tonic::IntoRequest<super::TransparentAddressBlockFilter>,
        ) -> std::result::Result<
            tonic::Response<
                tonic::codec::Streaming<::zcash_client_backend::proto::service::RawTransaction>,
            >,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTaddressTxids",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetTaddressTxids",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn get_taddress_balance(
            &mut self,
            request: impl tonic::IntoRequest<super::AddressList>,
        ) -> std::result::Result<tonic::Response<super::Balance>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTaddressBalance",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetTaddressBalance",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_taddress_balance_stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::Address>,
        ) -> std::result::Result<tonic::Response<super::Balance>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTaddressBalanceStream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetTaddressBalanceStream",
            ));
            self.inner.client_streaming(req, path, codec).await
        }
        /// Return the compact transactions currently in the mempool; the results
        /// can be a few seconds out of date. If the Exclude list is empty, return
        /// all transactions; otherwise return all *except* those in the Exclude list
        /// (if any); this allows the client to avoid receiving transactions that it
        /// already has (from an earlier call to this rpc). The transaction IDs in the
        /// Exclude list can be shortened to any number of bytes to make the request
        /// more bandwidth-efficient; if two or more transactions in the mempool
        /// match a shortened txid, they are all sent (none is excluded). Transactions
        /// in the exclude list that don't exist in the mempool are ignored.
        pub async fn get_mempool_tx(
            &mut self,
            request: impl tonic::IntoRequest<super::Exclude>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::CompactTx>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetMempoolTx",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetMempoolTx",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Return a stream of current Mempool transactions. This will keep the output stream open while
        /// there are mempool transactions. It will close the returned stream when a new block is mined.
        pub async fn get_mempool_stream(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::Empty>,
        ) -> std::result::Result<
            tonic::Response<
                tonic::codec::Streaming<::zcash_client_backend::proto::service::RawTransaction>,
            >,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetMempoolStream",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetMempoolStream",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        /// GetTreeState returns the note commitment tree state corresponding to the given block.
        /// See section 3.7 of the Zcash protocol specification. It returns several other useful
        /// values also (even though they can be obtained using GetBlock).
        /// The block can be specified by either height or hash.
        pub async fn get_tree_state(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::BlockId>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::TreeState>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTreeState",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetTreeState",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_latest_tree_state(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::Empty>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::TreeState>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLatestTreeState",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetLatestTreeState",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Returns a stream of information about roots of subtrees of the note commitment tree
        /// for the specified shielded protocol (Sapling or Orchard).
        pub async fn get_subtree_roots(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSubtreeRootsArg>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::SubtreeRoot>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetSubtreeRoots",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetSubtreeRoots",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn get_address_utxos(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAddressUtxosArg>,
        ) -> std::result::Result<tonic::Response<super::GetAddressUtxosReplyList>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetAddressUtxos",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetAddressUtxos",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_address_utxos_stream(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAddressUtxosArg>,
        ) -> std::result::Result<
            tonic::Response<
                tonic::codec::Streaming<
                    ::zcash_client_backend::proto::service::GetAddressUtxosReply,
                >,
            >,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetAddressUtxosStream",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetAddressUtxosStream",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Return information about this lightwalletd instance and the blockchain
        pub async fn get_lightd_info(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::Empty>,
        ) -> std::result::Result<tonic::Response<super::LightdInfo>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLightdInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "GetLightdInfo",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Testing-only, requires lightwalletd --ping-very-insecure (do not enable in production)
        pub async fn ping(
            &mut self,
            request: impl tonic::IntoRequest<super::Duration>,
        ) -> std::result::Result<tonic::Response<super::PingResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.CompactTxStreamer/Ping",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.CompactTxStreamer",
                "Ping",
            ));
            self.inner.unary(req, path, codec).await
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DarksideMetaState {
    #[prost(int32, tag = "1")]
    pub sapling_activation: i32,
    #[prost(string, tag = "2")]
    pub branch_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub chain_name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub start_sapling_commitment_tree_size: u32,
    #[prost(uint32, tag = "5")]
    pub start_orchard_commitment_tree_size: u32,
}
/// A block is a hex-encoded string.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DarksideBlock {
    #[prost(string, tag = "1")]
    pub block: ::prost::alloc::string::String,
}
/// DarksideBlocksURL is typically something like:
/// <https://raw.githubusercontent.com/zcash-hackworks/darksidewalletd-test-data/master/basic-reorg/before-reorg.txt>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DarksideBlocksUrl {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
}
/// DarksideTransactionsURL refers to an HTTP source that contains a list
/// of hex-encoded transactions, one per line, that are to be associated
/// with the given height (fake-mined into the block at that height)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DarksideTransactionsUrl {
    #[prost(int32, tag = "1")]
    pub height: i32,
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DarksideHeight {
    #[prost(int32, tag = "1")]
    pub height: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DarksideEmptyBlocks {
    #[prost(int32, tag = "1")]
    pub height: i32,
    #[prost(int32, tag = "2")]
    pub nonce: i32,
    #[prost(int32, tag = "3")]
    pub count: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DarksideSubtreeRoots {
    #[prost(enumeration = "ShieldedProtocol", tag = "1")]
    pub shielded_protocol: i32,
    #[prost(uint32, tag = "2")]
    pub start_index: u32,
    #[prost(message, repeated, tag = "3")]
    pub subtree_roots: ::prost::alloc::vec::Vec<SubtreeRoot>,
}
/// Generated client implementations.
pub mod darkside_streamer_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    /// Darksidewalletd maintains two staging areas, blocks and transactions. The
    /// Stage\*() gRPCs add items to the staging area; ApplyStaged() "applies" everything
    /// in the staging area to the working (operational) state that the mock zcashd
    /// serves; transactions are placed into their corresponding blocks (by height).
    #[derive(Debug, Clone)]
    pub struct DarksideStreamerClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl DarksideStreamerClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> DarksideStreamerClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> DarksideStreamerClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                    http::Request<tonic::body::Body>,
                    Response = http::Response<
                        <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                    >,
                >,
            <T as tonic::codegen::Service<http::Request<tonic::body::Body>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            DarksideStreamerClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Reset reverts all darksidewalletd state (active block range, latest height,
        /// staged blocks and transactions) and lightwalletd state (cache) to empty,
        /// the same as the initial state. This occurs synchronously and instantaneously;
        /// no reorg happens in lightwalletd. This is good to do before each independent
        /// test so that no state leaks from one test to another.
        /// Also sets (some of) the values returned by GetLightdInfo(). The Sapling
        /// activation height specified here must be where the block range starts.
        pub async fn reset(
            &mut self,
            request: impl tonic::IntoRequest<super::DarksideMetaState>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/Reset",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "Reset",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// StageBlocksStream accepts a list of blocks and saves them into the blocks
        /// staging area until ApplyStaged() is called; there is no immediate effect on
        /// the mock zcashd. Blocks are hex-encoded. Order is important, see ApplyStaged.
        pub async fn stage_blocks_stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::DarksideBlock>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/StageBlocksStream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "StageBlocksStream",
            ));
            self.inner.client_streaming(req, path, codec).await
        }
        /// StageBlocks is the same as StageBlocksStream() except the blocks are fetched
        /// from the given URL. Blocks are one per line, hex-encoded (not JSON).
        pub async fn stage_blocks(
            &mut self,
            request: impl tonic::IntoRequest<super::DarksideBlocksUrl>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/StageBlocks",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "StageBlocks",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// StageBlocksCreate is like the previous two, except it creates 'count'
        /// empty blocks at consecutive heights starting at height 'height'. The
        /// 'nonce' is part of the header, so it contributes to the block hash; this
        /// lets you create identical blocks (same transactions and height), but with
        /// different hashes.
        pub async fn stage_blocks_create(
            &mut self,
            request: impl tonic::IntoRequest<super::DarksideEmptyBlocks>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/StageBlocksCreate",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "StageBlocksCreate",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// StageTransactionsStream stores the given transaction-height pairs in the
        /// staging area until ApplyStaged() is called. Note that these transactions
        /// are not returned by the production GetTransaction() gRPC until they
        /// appear in a "mined" block (contained in the active blockchain presented
        /// by the mock zcashd).
        pub async fn stage_transactions_stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = ::zcash_client_backend::proto::service::RawTransaction,
            >,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/StageTransactionsStream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "StageTransactionsStream",
            ));
            self.inner.client_streaming(req, path, codec).await
        }
        /// StageTransactions is the same except the transactions are fetched from
        /// the given url. They are all staged into the block at the given height.
        /// Staging transactions to different heights requires multiple calls.
        pub async fn stage_transactions(
            &mut self,
            request: impl tonic::IntoRequest<super::DarksideTransactionsUrl>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/StageTransactions",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "StageTransactions",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// ApplyStaged iterates the list of blocks that were staged by the
        /// StageBlocks\*() gRPCs, in the order they were staged, and "merges" each
        /// into the active, working blocks list that the mock zcashd is presenting
        /// to lightwalletd. Even as each block is applied, the active list can't
        /// have gaps; if the active block range is 1000-1006, and the staged block
        /// range is 1003-1004, the resulting range is 1000-1004, with 1000-1002
        /// unchanged, blocks 1003-1004 from the new range, and 1005-1006 dropped.
        ///
        /// After merging all blocks, ApplyStaged() appends staged transactions (in
        /// the order received) into each one's corresponding (by height) block
        /// The staging area is then cleared.
        ///
        /// The argument specifies the latest block height that mock zcashd reports
        /// (i.e. what's returned by GetLatestBlock). Note that ApplyStaged() can
        /// also be used to simply advance the latest block height presented by mock
        /// zcashd. That is, there doesn't need to be anything in the staging area.
        pub async fn apply_staged(
            &mut self,
            request: impl tonic::IntoRequest<super::DarksideHeight>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/ApplyStaged",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "ApplyStaged",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Calls to the production gRPC SendTransaction() store the transaction in
        /// a separate area (not the staging area); this method returns all transactions
        /// in this separate area, which is then cleared. The height returned
        /// with each transaction is -1 (invalid) since these transactions haven't
        /// been mined yet. The intention is that the transactions returned here can
        /// then, for example, be given to StageTransactions() to get them "mined"
        /// into a specified block on the next ApplyStaged().
        pub async fn get_incoming_transactions(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::Empty>,
        ) -> std::result::Result<
            tonic::Response<
                tonic::codec::Streaming<::zcash_client_backend::proto::service::RawTransaction>,
            >,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/GetIncomingTransactions",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "GetIncomingTransactions",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Clear the incoming transaction pool.
        pub async fn clear_incoming_transactions(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::Empty>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/ClearIncomingTransactions",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "ClearIncomingTransactions",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Add a GetAddressUtxosReply entry to be returned by GetAddressUtxos().
        /// There is no staging or applying for these, very simple.
        pub async fn add_address_utxo(
            &mut self,
            request: impl tonic::IntoRequest<
                ::zcash_client_backend::proto::service::GetAddressUtxosReply,
            >,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/AddAddressUtxo",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "AddAddressUtxo",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Clear the list of GetAddressUtxos entries (can't fail)
        pub async fn clear_address_utxo(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::Empty>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/ClearAddressUtxo",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "ClearAddressUtxo",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Adds a GetTreeState to the tree state cache
        pub async fn add_tree_state(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::TreeState>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/AddTreeState",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "AddTreeState",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Removes a GetTreeState for the given height from cache if present (can't fail)
        pub async fn remove_tree_state(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::BlockId>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/RemoveTreeState",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "RemoveTreeState",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Clear the list of GetTreeStates entries (can't fail)
        pub async fn clear_all_tree_states(
            &mut self,
            request: impl tonic::IntoRequest<::zcash_client_backend::proto::service::Empty>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/ClearAllTreeStates",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "ClearAllTreeStates",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Sets the subtree roots cache (for GetSubtreeRoots),
        /// replacing any existing entries
        pub async fn set_subtree_roots(
            &mut self,
            request: impl tonic::IntoRequest<super::DarksideSubtreeRoots>,
        ) -> std::result::Result<
            tonic::Response<::zcash_client_backend::proto::service::Empty>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cash.z.wallet.sdk.rpc.DarksideStreamer/SetSubtreeRoots",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "cash.z.wallet.sdk.rpc.DarksideStreamer",
                "SetSubtreeRoots",
            ));
            self.inner.unary(req, path, codec).await
        }
    }
}
